.TH OPENCC "1" "2010 年 6 月" "opencc " "用户命令"
.SH NAME
opencc \- 简繁中文转换工具
.SH DESCRIPTION
开放式中文转换 (OpenCC) 命令行工具
.SS "用法："
.HP
opencc [\-i 输入文件] [\-o 输出文件] [\-c 配置文件]
.HP
\fB\-i\fR
从输入文件读取原始文本。
.HP
\fB\-o\fR
将转换好的文本写入输出文件。
.HP
\fB\-c\fR
从配置文件加载字典配置。
.IP
注意：
.IP
若未设置输入文件则读取来自标准输入的文本，若未设置输出文件则写入到标准输出。
.IP
若未设置配置文件则加载默认配置 (zhs2zht.ini)。
.PP
开放式中文转换 (OpenCC) 命令行工具
.SH "继续阅读"
.BR iconv (1)
