.TH OPENCC "1" "June 2010" "opencc " "User Commands"
.SH NAME
opencc \- simplified-traditional chinese conversion tool
.SH DESCRIPTION
Open Chinese Convert (OpenCC) Command Line Tool
.SS "Usage:"
.HP
opencc [\-i input_file] [\-o output_file] [\-c config_file]
.HP
\fB\-i\fR
Read original text from input_file.
.HP
\fB\-o\fR
Write converted text to output_file.
.HP
\fB\-c\fR
Load dictionary configuration from config_file.
.IP
Note:
.IP
Text from standard input will be read if input_file is not set and will be written to standard output if output_file is not set.
.IP
Default configuration(zhs2zht.ini) will be load if config_file is not set.
.PP
Open Chinese Convert (OpenCC) Command Line Tool
.SH "SEE ALSO"
.BR iconv (1)
