.TH OPENCC "1" "June 2010" "opencc " "User Commands"
.SH NAME
opencc \- simplified-traditional chinese conversion tool
.SH DESCRIPTION
Open Chinese Convert (OpenCC) Command Line Tool
Version 0.0.2
.SS "Usage:"
.IP
opencc [\-i input_file] [\-o output_file]
.HP
\fB\-i\fR
.IP
Read original text from input_file.
.HP
\fB\-o\fR
.IP
Write converted text to output_file.
.IP
Note:
.IP
Text from standard input will be read if input_file is not set
and will be written to standard output if output_file is not set.
.PP
Open Chinese Convert (OpenCC) Command Line Tool
Version 0.0.2
.SH "SEE ALSO"
.BR iconv (1)
