.TH OPENCC_DICT "1" "June 2010" "opencc_dict " "User Commands"
.SH NAME
opencc_dict \- open chinese convert dictionary tool
.SH DESCRIPTION
Open Chinese Convert (OpenCC) Dictionary Tool
.SS "Usage:"
.HP
opencc_dict \fB\-i\fR input_file \fB\-o\fR output_file
.HP
\fB\-i\fR
Read data from input_file.
.HP
\fB\-o\fR
Write converted data to output_file.
.PP
Open Chinese Convert (OpenCC) Dictionary Tool
.SH "SEE ALSO"
.BR opencc (1)
