.TH OPENCC "1" "2010 年 6 月" "opencc " "用戶命令"
.SH NAME
opencc \- 簡繁中文轉換工具
.SH DESCRIPTION
開放式中文轉換 (OpenCC) 命令行工具
.SS "用法："
.HP
opencc [\-i 輸入文件] [\-o 輸出文件] [\-c 配置文件]
.HP
\fB\-i\fR
從輸入文件讀取原始文本。
.HP
\fB\-o\fR
將轉換好的文本寫入輸出文件。
.HP
\fB\-c\fR
從配置文件加載字典配置。
.IP
注意：
.IP
若未設置輸入文件則讀取來自標準輸入的文本，若未設置輸出文件則寫入到標準輸出。
.IP
若未設置配置文件則加載默認配置 (zhs2zht.ini)。
.PP
開放式中文轉換 (OpenCC) 命令行工具
.SH "繼續閱讀"
.BR iconv (1)

