.TH OPENCC_PHRASE_EXTRACT 1 "" "OPENCC" "开放中文转换"
.SH 名称
opencc_phrase_extract \- OpenCC 语句抓取工具
.
.SH 概要
.B opencc_phrase_extract
-o <文件> [--] [--version] [-h] <文件> ...
.
.SH 选项
.TP
.B -o <文件>,  --output <文件>
（必填） 输出文件
.
.TP
.B --,  --ignore_rest
忽略排在此选项后面的引数。
.
.TP
.B --version
显示版本信息然后退出。
.
.TP
.B -h,  --help
显示使用说明然后退出。
.
.TP
.B <文件>\fR （接受多个引数）
（必填） 输入文件
.
.SH 参见
opencc(1)
.
.SH 作者
Carbo Kuo <byvoid@byvoid.com>
