// For faster build
#include "marisa/trie.cc"
#include "marisa/agent.cc"
#include "marisa/grimoire/io/reader.cc"
#include "marisa/grimoire/io/writer.cc"
#include "marisa/grimoire/io/mapper.cc"
#include "marisa/grimoire/trie/louds-trie.cc"
#include "marisa/grimoire/trie/tail.cc"
#include "marisa/grimoire/vector/bit-vector.cc"
#include "marisa/keyset.cc"
